# Generated by Django 4.1.5 on 2023-01-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Навыки без описание будут добавляться как другие навыки'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Навык'),
        ),
    ]
