# Generated by Django 4.1.5 on 2023-01-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_skill_options_alter_skill_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to='user_images/%Y/%m/%d/%m/%s/', verbose_name='Фото профиля'),
        ),
    ]
