# Generated by Django 4.1.5 on 2023-02-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='users.profile', verbose_name='Подписки'),
        ),
    ]
