# Generated by Django 4.1.5 on 2023-01-12 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Демонстрационная ссылка')),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка на источник')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
