# Generated by Django 4.1.2 on 2023-03-10 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='project_images/%Y/%m/%d/%h/%S/', verbose_name='Фото')),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Демонстрационная ссылка')),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка на источник')),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее количество голосов')),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True, verbose_name='Соотношение голосов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('on_off_review', models.BooleanField(default=True, verbose_name='Комментарии Вкл/Выкл')),
                ('auther', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('dis_likes', models.ManyToManyField(blank=True, related_name='my_dislikes', to='users.profile', verbose_name='Дизлайки')),
                ('likes', models.ManyToManyField(blank=True, related_name='my_likes', to='users.profile', verbose_name='Лайки')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('auther', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_review', to='users.profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.review')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='users.profile'),
        ),
    ]
