# Generated by Django 4.1.5 on 2023-01-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tags_alter_project_options_project_vote_ratio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
