# Generated by Django 4.1.5 on 2023-01-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_image_alter_project_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='project_images/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
