# Generated by Django 4.1.5 on 2023-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_auther_review_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='on_off_review',
            field=models.BooleanField(default=True, verbose_name='Комментарии\nВкл/Выкл'),
        ),
    ]
