# Generated by Django 4.1.5 on 2023-01-31 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_email'),
        ('projects', '0009_project_on_off_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='on_off_review',
            field=models.BooleanField(default=True, verbose_name='Комментарии Вкл/Выкл'),
        ),
        migrations.AlterField(
            model_name='review',
            name='auther',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_review', to='users.profile'),
        ),
    ]
