# Generated by Django 4.1.5 on 2023-02-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_email'),
        ('projects', '0010_alter_project_on_off_review_alter_review_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, related_name='views', to='users.profile'),
        ),
    ]
