# Generated by Django 4.1.5 on 2023-02-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_email'),
        ('projects', '0011_project_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='users.profile'),
        ),
    ]
