# Generated by Django 4.1.5 on 2023-02-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='project_images/%Y/%m/%d/%h/%S/', verbose_name='Фото'),
        ),
    ]
